### ISSUE TITLE
passing babel options as object instead of babelrc

### ISSUE THREAD

**Issue by ezekielchentnik** [davidchase/buba#22]
@davidchase In the readme, says to use babelrc to add options for babel.  I'm running into an issue where im doing some server side rendering with React/Preact so I need jsx to be transformed.

I can get it to work using .babelrc, however, what do you think about allowing ability to pass babel options similar to bubleOptions ?

``` javascript
const bubleOptions ={jsx: 'h'}
const babelOptions = { "plugins": [["transform-react-jsx", { "pragma": "h" }]] }

require('buba/register')(bubleOptions, babelOptions)
const app = require('./app').default
// ... magic
```

**Comment by davidchase** [comment]
sounds good to me would you like to send in a PR?

//cc @TylorS any thoughts?

**Comment by TylorS** [comment]
:+1:

**Comment by ezekielchentnik** [comment]
I'll send in a PR this weekend!

**Comment by ezekielchentnik** [comment]
Just submitted PR #25 
Uncertain if this is the way we want to pass additional options or if individual arguments are a better choice.  This PR mimics how options are passed to .transformFile.  Also, this changes current api...

``` javascript
require('buba/register')({ buble: {}, babel: {} })
```

**Comment by davidchase** [comment]
i think since the PR is merge we can close this issue, thanks again for the help 😄

**Comment by davidchase** [comment]
publishing to npm soon
